display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: csp
subsystem: mid.cbf
telescope: SKA-mid

labels:
  app: ska-mid-cbf-deployment

global:
  minikube: false
  k3d: false
  exposeDatabaseDS: true
  exposeAllDS: false
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-dsconfig
      tag: 1.5.13
      pullPolicy: IfNotPresent